version: '2.10.2'

services:
  db:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=parsdb
      - POSTGRES_USER=stas
      - POSTGRES_PASSWORD=2110
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data:

